- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/5042/workspace/MavenAnsibleWebbApp1-CICD/target/MavenAnsibleWebbApp1.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebbApp1.war"
        remote_src: no
    - name: stop tomcat
      shell: /opt/tomcat/bin/shutdown.sh
      ignore_errors: yes
    - name: 	start tomcat
      shell: /opt/tomcat/bin/startup.sh
